name: CI

# Trigger the workflow on push or pull request, but only for the master branch
on:
  pull_request:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} ghc-${{ matrix.ghc }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            cabal: "3.0.0.0"
            ghc: "8.8.4"
          - os: macos-latest
            cabal: "3.0.0.0"
            ghc: "8.8.4"

    steps:
    - uses: actions/checkout@v2
      if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.ref == 'refs/heads/master'

    - uses: actions/setup-haskell@v1
      name: Setup Haskell
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    - uses: actions/cache@v1
      name: Cache ~/.cabal/store
      with:
        path: ~/.cabal/store
        key: ${{ runner.os }}-${{ matrix.ghc }}-cabal

    - name: Install OpenBLAS
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends libopenblas-dev

    - name: Cabal dependencies
      run: |
        cabal v2-update
        cabal v2-build --dependencies-only

    - name: Build
      run: |
        cabal v2-build --verbose --enable-tests --enable-benchmarks

    - name: Test
      run: |
        cabal v2-test --enable-tests --test-show-details=direct
